### ISSUE TITLE
missing icons 

### ISSUE THREAD

**Issue by jblumtritt** [cceh/owncloud-installation#2]
Icons zum Bearbeiten usw. neben dem Kalender werden nciht angzeigt.
![owncloud-icons-missing](https://cloud.githubusercontent.com/assets/3205396/5358064/1ac30a5c-7fb0-11e4-9413-1c3043005383.png)

**Comment by pdaengeli** [comment]
The icons in this particular view are shown for me (OS X 10.7.5: Safari 6.1.6, Firefox 28; OS X 10.6.8: FirefoxDeveloperEdition 36.0.a2; Ubuntu: Firefox 34.0).

Does this problem persist for you?

**Comment by jblumtritt** [comment]
I can see them too now. Any other missing Icons?

**Comment by gioele** [comment]
It doesn't seem so, we can open another in case we see more missing icons.
