### ISSUE TITLE
Install a valid TLS certificate

### ISSUE THREAD

**Issue by gioele** [cceh/owncloud-installation#5]
The current self-signed certificate should be replaced with the proper one received from RRZK.

**Comment by jblumtritt** [comment]
done

**Comment by pdaengeli** [comment]
When opening the client application I am prompted with a warning that reads:

```
 SSL Connection
 Warnings about current SSL Connection:
 The issuer certificate of a locally looked up certificate could not be found
 The root CA certificate is not trusted for this purpose
 No certificates could be verified
 with Certificate cloud.cceh.uni-koeln.de
 Organization: Universitaet zu Koeln
 Unit: <not specified>
 Country: DE
 Fingerprint (MD5): 6f:10:91:96:61:f3:36:77:7b:13:7f:13:0d:63:61:db
 Fingerprint (SHA1): 5d:2b:c6:95:83:d8:44:5f:26:9d:c8:6f:e4:96:b3:91:a2:cc:88:ef

 Effective Date: Mon Nov 17 13:28:16 2014 GMT
 Expiry Date: Tue Jul 9 23:59:00 2019 GMT
 Issuer: UniKoeln CA
 Organization: Universitaet zu Koeln
 Unit: 
 Country: DE
```

In order to launch the application I have to accept `Trust this certificate anyway`. A client restart has no effect; it remains to be seen whether this behavior is transient.

**Comment by gioele** [comment]
This problem is very likely caused by the lack of some intermediate certificate. Probably not all the needed CA are included in older systems.

This certificate requires the following chain of certificates
- UniKoeln CA 
- DFN-Verein PCA Global-G01
- Deutsche Telekom Root CA 2

@jblumtritt: I suppose the certificate issuer can provide you with the missing certificates in PEM format.

**Comment by pdaengeli** [comment]
At the moment I cannot reproduce this problem. The client application launches without any certificate issues. Also, the certificates are listed as valid using system defaults on my systems.

**Comment by jblumtritt** [comment]
@gioele could you try again. the chain-file with intermediate certs was missing UniKoeln CA. hopefully fixed.

**Comment by jblumtritt** [comment]
![qualys_ssl_labs_-_projects_ssl_server_test_cloud cceh uni-koeln de_-_2014-12-17_15 47 24](https://cloud.githubusercontent.com/assets/3205396/5472745/16667b4c-8604-11e4-84af-54f28c93f962.png)
