### ISSUE TITLE
Plan the structure of the directories

### ISSUE THREAD

**Issue by gioele** [cceh/owncloud-installation#6]
How should the directory structure look like in our ownCloud?

@PatrickSahle: opinions?

**Comment by jblumtritt** [comment]
Facts:
- You can grant access to a user group on any level
- It is impossible to revoke access from someone on a lower level if you already shared a parent folder with him.
- A shared folder always shows up on root level (except for the owner of the folder)

Recommended folder structure:
- cceh
  - projekte
    - p1
  - kooperationen
    - k1 (shared with cceh by default, + external group k1)
- cceh-admin
- ...

groups:
- cceh
- cceh-admin
- groups for external partners: k1, k2, k3 ...
