### ISSUE TITLE
Check if group calendars are possible

### ISSUE THREAD

**Issue by gioele** [cceh/owncloud-installation#8]
Is it possible to have group calendars?

Whether it is possible and how to do so should be documented in the Wiki.

**Comment by pdaengeli** [comment]
There are no group calendars as such, but it is possible to share calendars with users and groups.

It seems advisable that the root user (the one that also owns all default directories and has the largest quota) creates one or severals calendars that are shared with the respective group(s).

This was successfully tested with the user `ccehcloud`and its calendar `cceh-shared`. The calendar is listed and editable for other users.
