### ISSUE TITLE
Create "cceh" user that owns all the shared documents and calendars

### ISSUE THREAD

**Issue by gioele** [cceh/owncloud-installation#9]
The quota of the `cceh` user will be used as the main quota of the group. Every document created inside the `CCeH` root folder (owned by the `cceh` user) will count against the quota of the `cceh` user, not of the person uploading the file.

In addition to this people will have a smallish quota (500MB?) for their personal files.

**Comment by pdaengeli** [comment]
A user was created and used for the creation of the main folder and the subsequent initial synchronization on 27th Feb, 2015.
